/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminEnquiriesRouteImport } from './routes/admin/enquiries'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminSectionsRouteImport } from './routes/admin/sections'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRoomsIndexRouteImport } from './routes/admin/rooms/index'
import { Route as AdminRoomsRoomIdRouteImport } from './routes/admin/rooms/$roomId'
import { Route as AdminRoomsNewRouteImport } from './routes/admin/rooms/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSectionsRoute = AdminSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRoomsIndexRoute = AdminRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRoomsRoomIdRoute = AdminRoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRoomsNewRoute = AdminRoomsNewRouteImport.update({
  id: '/rooms/new',
  path: '/rooms/new',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/rooms/$roomId': typeof AdminRoomsRoomIdRoute
  '/admin/rooms/new': typeof AdminRoomsNewRoute
  '/admin/rooms/': typeof AdminRoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/rooms/$roomId': typeof AdminRoomsRoomIdRoute
  '/admin/rooms/new': typeof AdminRoomsNewRoute
  '/admin/rooms': typeof AdminRoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/rooms/$roomId': typeof AdminRoomsRoomIdRoute
  '/admin/rooms/new': typeof AdminRoomsNewRoute
  '/admin/rooms/': typeof AdminRoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/enquiries'
    | '/admin/login'
    | '/admin/media'
    | '/admin/sections'
    | '/admin/settings'
    | '/admin/'
    | '/admin/rooms/$roomId'
    | '/admin/rooms/new'
    | '/admin/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/enquiries'
    | '/admin/login'
    | '/admin/media'
    | '/admin/sections'
    | '/admin/settings'
    | '/admin'
    | '/admin/rooms/$roomId'
    | '/admin/rooms/new'
    | '/admin/rooms'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/enquiries'
    | '/admin/login'
    | '/admin/media'
    | '/admin/sections'
    | '/admin/settings'
    | '/admin/'
    | '/admin/rooms/$roomId'
    | '/admin/rooms/new'
    | '/admin/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sections': {
      id: '/admin/sections'
      path: '/sections'
      fullPath: '/admin/sections'
      preLoaderRoute: typeof AdminSectionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rooms/': {
      id: '/admin/rooms/'
      path: '/rooms'
      fullPath: '/admin/rooms/'
      preLoaderRoute: typeof AdminRoomsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rooms/$roomId': {
      id: '/admin/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/admin/rooms/$roomId'
      preLoaderRoute: typeof AdminRoomsRoomIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rooms/new': {
      id: '/admin/rooms/new'
      path: '/rooms/new'
      fullPath: '/admin/rooms/new'
      preLoaderRoute: typeof AdminRoomsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminSectionsRoute: typeof AdminSectionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminRoomsRoomIdRoute: typeof AdminRoomsRoomIdRoute
  AdminRoomsNewRoute: typeof AdminRoomsNewRoute
  AdminRoomsIndexRoute: typeof AdminRoomsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminSectionsRoute: AdminSectionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminRoomsRoomIdRoute: AdminRoomsRoomIdRoute,
  AdminRoomsNewRoute: AdminRoomsNewRoute,
  AdminRoomsIndexRoute: AdminRoomsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
